version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: local-postgres
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"   # usamos 5433 en Windows para evitar choques con otro Postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
