"""add student_profiles

Revision ID: 4a6331f720b1
Revises: 448e4d241a94
Create Date: 2025-09-02 23:12:25.069902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a6331f720b1'
down_revision = '448e4d241a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('cash_balance', sa.Integer(), nullable=True),
    sa.Column('salary_monthly', sa.Integer(), nullable=True),
    sa.Column('has_car', sa.Boolean(), nullable=True),
    sa.Column('car_payment_monthly', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_profiles')
    # ### end Alembic commands ###
