"""module progress + activity state

Revision ID: c1473b0dcd4c
Revises: 4a6331f720b1
Create Date: 2025-09-03 00:55:12.982774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1473b0dcd4c'
down_revision = '4a6331f720b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('current_pos', sa.Integer(), nullable=True),
    sa.Column('score_total', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('module_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_module_progress_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_module_progress_user_id'), ['user_id'], unique=False)

    op.create_table('activity_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('last_submission_json', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_state_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_state_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_state_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_state_activity_id'))

    op.drop_table('activity_state')
    with op.batch_alter_table('module_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_module_progress_module_id'))

    op.drop_table('module_progress')
    # ### end Alembic commands ###
